### ISSUE TITLE
Rendering problem when used with Google Maps Android API v2

### ISSUE THREAD

**Issue by lexer** [SimonVT/android-menudrawer#48] opened 2012-12-26 05:58 UTC
If there is map (v2) inside content area sliding menu is not rendered and you see just a black background.

I have faced that issue on Galaxy S3 and many other 2.3 phones. However on Galaxy Nexus with 4.2 everything is ok.

I have attached screenshot that illustrates the problem.
![map_problem](https://f.cloud.github.com/assets/108267/30817/327774c4-4f21-11e2-9791-0695e72d20da.png)

**Comment by SimonVT** [comment] 2012-12-26 16:58
Probably duplicate of issue #24.

**Comment by lexer** [comment] 2013-01-04 08:14
As you see from screenshot I have supplied rendering is ok in the areas where map has overlay (look at the bottom of screen).

So It is possible to fix problem if we can add transparent layer over the scrollable area. 

During the scrolling we should make transparent layer visible otherwise set its visibility to "gone".

Any ideas how to implement that?

**Comment by lexer** [comment] 2013-01-04 09:08
I discovered an easy hack.

You simply create RelativeLayout with content placeholder and transparent overlay that always visible. Every click events inside content works ok and bug also disappears:

```
    <RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
                    android:layout_width="match_parent"
                    android:layout_height="match_parent"
            >
        <FrameLayout
                android:id="@+id/fragment_placeholder"
                android:layout_width="match_parent"
                android:layout_height="match_parent">

        </FrameLayout>

        <FrameLayout android:layout_width="match_parent"
                     android:layout_height="match_parent"
                     android:background="@android:color/transparent">

        </FrameLayout>
    </RelativeLayout>
```

What you think?

**Comment by mgrzechocinski** [comment] 2013-02-20 23:34
I've also faced with that. Above solution works ok at first sight, but for example on Samsung Galaxy S3 there is another bug (movie): http://cl.ly/3o1c1V1Z3B3o

Any hints?

**Comment by czechnology** [comment] 2013-02-27 00:37
I'm just facing this problem too. It works fine on my 4.1 device on which I've developed my app but now during final testing I've found out that the menu is unusable on 2.2.

Would be thankful for any solutions!

**Comment by JakeWharton** [comment] 2013-02-27 00:37
Have you tried with revision 5 which was released today?

**Comment by czechnology** [comment] 2013-02-27 00:46
I have just now worked this into the samples (to see if it's not caused by my app) app which I downloaded just minutes ago.  
Is it the latest revision if I download the ZIP directly from github here?

Just for clarity (or if I'm not doing something wrong myself), except for the manifest changes required for the maps API I've changed the layout:

```
<?xml version="1.0" encoding="utf-8"?>
<!-- /res/layout/activity_contentsample.xml -->
<fragment xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:map="http://schemas.android.com/apk/res-auto"
    android:id="@+id/map"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    class="com.google.android.gms.maps.SupportMapFragment" />
```

And changed the Activity accordingly: to extend `FragmentActivity` and comment out the last two lines of `onCreate(Bundle)`.

Interesting thing - the faster I draw the menu, the narrower the black rectangle is.

**Comment by nicopico-dev** [comment] 2013-02-27 17:54
Testing with Google Play Service rev. 5 and Android Support Library rev. 12, the issue is still here on Android 2.2.
It seems to work correctly on Android 4.2.2

**Comment by czechnology** [comment] 2013-03-05 11:16
Does anyone know from which OS version it works ok? So that I could develop a different menu solution for the older devices. Because this is the only thing stopping me from releasing my app...

**Comment by SimonVT** [comment] 2013-03-05 20:02
Does anyone have a complete sample I can use to debug this?

**Comment by czechnology** [comment] 2013-03-07 16:10
In ADT:
1. Download and import the Google Play services SDK as described in the [manual](http://developer.android.com/google/play-services/setup.html).
2. Download the [menudrawer repository](https://github.com/SimonVT/android-menudrawer/archive/master.zip).
3. Import the menudrawer `library` and `SamplesActivity` projects into Eclipse workspace, set the `SamplesActivity` project to require Google Play services and MenuDrawer libraries.
4. Modify the following three files in the `SamplesActivity` project:
- `/Androidmanifest.xml` changes:

```
@@ -6,11 +6,25 @@

     <uses-sdk android:minSdkVersion="7" android:targetSdkVersion="17" />

+    <permission
+        android:name="net.simonvt.menudrawer.samples.permission.MAPS_RECEIVE"
+        android:protectionLevel="signature" />
+    <uses-permission android:name="net.simonvt.menudrawer.samples.permission.MAPS_RECEIVE" />
+    <uses-permission android:name="android.permission.INTERNET" />
+    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
+    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
+    <uses-permission android:name="com.google.android.providers.gsf.permission.READ_GSERVICES" />
+    <uses-feature
+        android:glEsVersion="0x00020000"
+        android:required="true"/>
     <application
         android:label="@string/app_name"
         android:icon="@drawable/ic_launcher"
         android:theme="@style/SampleTheme">
+        <meta-data
+            android:name="com.google.android.maps.v2.API_KEY"
+            android:value="YOUR_API_KEY_HERE"/>

         <activity
             android:name="SamplesActivity"
             android:label="@string/app_name"
```

(you need to change `YOUR_API_KEY_HERE` to a [valid API key](https://developers.google.com/maps/documentation/android/start#the_google_maps_api_key))
- `/src/net/simonvt/menudrawer/samples/ContentSample.java` changes:

```
@@ -1,10 +1,12 @@
 package net.simonvt.menudrawer.samples;

 import net.simonvt.menudrawer.MenuDrawer;

-import android.app.Activity;
 import android.os.Build;
 import android.os.Bundle;
+import android.support.v4.app.FragmentActivity;
 import android.view.MenuItem;
 import android.view.View;
 import android.view.ViewGroup;
 import android.widget.AbsListView;
 import android.widget.AdapterView;
 import android.widget.BaseAdapter;
 import android.widget.ListView;
 import android.widget.TextView;

-public class ContentSample extends Activity {
+public class ContentSample extends FragmentActivity {

     private static final String STATE_ACTIVE_POSITION = "net.simonvt.menudrawer.samples.ContentSample.activePosition";
     private static final String STATE_CONTENT_TEXT = "net.simonvt.menudrawer.samples.ContentSample.contentText";

@@ -80,8 +79,6 @@
             getActionBar().setDisplayHomeAsUpEnabled(true);
         }

-        mContentTextView = (TextView) findViewById(R.id.contentText);
-        mContentTextView.setText(mContentText);
     }
```
- `/res/layout/activity_contentsample.xml` should look like this:

```
<?xml version="1.0" encoding="utf-8"?>
<fragment xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:map="http://schemas.android.com/apk/res-auto"
    android:id="@+id/map"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    class="com.google.android.gms.maps.SupportMapFragment" />
```

---

Compile, install and choose "Content Sample".

**Comment by czechnology** [comment] 2013-03-19 13:37
Any ideas?

**Comment by leninZ** [comment] 2013-03-22 21:35
The solution i found to solve this is adding an image with the size of the fragment and set his android: visibility to "invisible". isn't beauty, but it works.

```
<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android" xmlns:tools="http://schemas.android.com/tools" android:layout_width="match_parent" android:layout_height="match_parent" tools:context=".Main" >
        <fragment
        android:id="@+id/map"
        android:name="com.google.android.gms.maps.MapFragment"
        android:layout_width="fill_parent"
        android:layout_height="fill_parent"
        class="com.google.android.gms.maps.SupportMapFragment" />

        <ImageView 
         android:layout_width="fill_parent"
         android:layout_height="fill_parent"
         android:visibility="invisible" />

</RelativeLayout>
```

**Comment by ljammala** [comment] 2013-04-25 16:12
I am still having this issue on Motorola Droid X. Anybody has any solution?

**Comment by levint** [comment] 2013-04-26 10:09
Able to reproduce on both Galaxy S and SIII. This seriously needs to be fixed.

**Comment by jdiggidy** [comment] 2013-05-06 16:46
Victoreta's solution worked for me.  I've only tested on HTC Incredible 2 running 2.3 thus far.

**Comment by djunod** [comment] 2013-07-19 22:30
Victoreta's solution does _not_ work for me.  Tried on a Nexus One running 2.3.6, Samsung GT-I9100 running 2.3.3.

**Comment by nodinosaur** [comment] 2013-07-26 12:07
If the MapFragment is being added by XML try setting the 
<code>xmlns:map="http://schemas.android.com/apk/res-auto"
map:zOrderOnTop="true"</code>

or programatically
<code>GoogleMapOptions mapOptions = new GoogleMapOptions();
mapOptions.zOrderOnTop(true);
SupportMapFragment.newInstance(mapOptions);</code>
Tested on a Samsung -GT i9100 on OS 2.3.4 and works well

**Comment by czechnology** [comment] 2013-07-29 11:05
@nodinosaur Unfortunately, that also hides my `ActionBar`.

**Comment by nodinosaur** [comment] 2013-07-30 08:25
@czechnology Yeah, I discovered the same myself recently. I don't understand how Google regard this as "acceptable". I doubt we'd see this issue on iOS, but I could be wrong.

**Comment by czechnology** [comment] 2013-07-30 08:33
I'm currently spreading a [test app](http://share.czechnology.cz/android/menudrawertest.apk) to figure out which devices are affected by this.

List so far - **working**:
- _API 17_: Jelly Bean 4.2.2 (Nexus 7)
- _API 16_: Jelly Bean 4.1.2 (Samsung Note II), Jelly Bean 4.1.2 (Samsung Galaxy S II)

**not working**:
- _API 10_: Gingerbread 2.3.7 (Motorola Defy+)
- _API 8_: Froyo 2.2 (Dell Streak)

For the non-compatible devices, I put the `MenuListView` instance in a `Dialog` instead (only requires changing the background color).

**Comment by felixb** [comment] 2013-08-16 08:26
Working: 
- API 17: N4
- API 17: tf101

Not working:
- API 10: HTC G2

**Comment by felixb** [comment] 2013-08-16 08:27
The gist from issue #24 fixed it for my HTC G2.

https://gist.github.com/groodt/5181980

**Comment by SimonVT** [comment] 2013-08-28 14:58
Seems like a underlying issue with SurfaceView, the maps api moved away from it where possible: https://code.google.com/p/gmaps-api-issues/issues/detail?id=4659#c35

I'm closing this, I wont be making any changes anyway.

**Closed as completed by SimonVT** 2013-08-28 14:58 UTC

**Comment by ArkadySladkoff** [comment] 2015-06-27 19:04
My solution: on fragment xmlns:map="http://schemas.android.com/apk/res-auto" map:zOrderOnTop="false"
