### ISSUE TITLE
scrolling listview in menu changes background color to white

### ISSUE THREAD

**Issue by kenyee** [SimonVT/android-menudrawer#64] opened 2013-01-29 03:48 UTC
Looks like menudrawer expects any context to have a background color of white?

I was testing out a listview in the menu like what you see w/ SlideMenu and when you scroll, the entire background turns white (it's normally a dark grey).  It sometimes gets stuck w/ a white background.

For the latter stuck background issue, you also see it sometimes with the static drawer sample...just try scrolling it up/down a bunch of times (I was testing on an old Moto Cliq w/ Android 2.1).

**Comment by SimonVT** [comment] 2013-01-29 05:33
Duplicate of #52

**Closed as completed by SimonVT** 2013-01-29 05:33 UTC
