### ISSUE TITLE
Menu drawer is higlighting all items on the list on scroll

### ISSUE THREAD

**Issue by akemalfirdaus** [SimonVT/android-menudrawer#53] opened 2013-01-04 08:45 UTC
I am not sure how to say this but every time when I try to scroll the list, the item will all be highlighted making all the text invisible until the user clicks on one of the item.

**Comment by ghost** [comment] 2013-01-04 09:14
Duplicate of #52 

@SimonVT : That's because it's a listview: http://android-developers.blogspot.com/2009/01/why-is-my-list-black-android.html

**Comment by akemalfirdaus** [comment] 2013-01-04 09:23
@iontech On which file do I edit the code? Because none of the XML Layouts I am using contains ListView, only TextView and Layouts.

**Comment by ghost** [comment] 2013-01-04 09:45
@akemalfirdaus What list do you have, then?

**Closed as completed** 2013-01-04 10:09 UTC

**Comment by akemalfirdaus** [comment] 2013-01-04 10:47
@iontech whoops my bad there was a list, but it was put there programmatically. Didn't notice before. So that fixed it.

**Comment by ghost** [comment] 2013-01-04 10:50
Cool. :smiley:
