### ISSUE TITLE
Rotation while using Right Menu distorts content

### ISSUE THREAD

**Issue by akshaydashrath** [SimonVT/android-menudrawer#72] opened 2013-02-05 15:49 UTC
![2013-02-05 15 47 38](https://f.cloud.github.com/assets/109231/127924/7d9f4ff8-6fab-11e2-9b38-7387acfbc52a.png)
![2013-02-05 15 47 44](https://f.cloud.github.com/assets/109231/127926/8403acc2-6fab-11e2-92b6-fef092b84e11.png)
![2013-02-05 15 47 50](https://f.cloud.github.com/assets/109231/127928/870b442a-6fab-11e2-949f-6a01a9d10e39.png)

**Comment by akshaydashrath** [comment] 2013-02-05 15:56
It appears that the offset to restore state of the menu does'nt take into account that its the right menu and offsets the menu by the menu width to the right (i.e. as if it were the left menu drawer)

**Comment by levinotik** [comment] 2013-02-06 04:45
I can confirm that. Here's what running the RightDrawer sample looks like after rotating to landscape and back to portrait.

![Screenshot_2013-02-05-23-44-05](https://f.cloud.github.com/assets/514174/130375/eff56f26-7017-11e2-9bd2-83a1a5b50450.png)

Pressing the overflow button again repositions the content without displaying the menudrawer.

**Comment by levinotik** [comment] 2013-02-06 05:25
The menu also becomes not visibile when you switch orientations. From the other samples, it appears the behavior is that the drawer remains open through orientation changes.

**Comment by levinotik** [comment] 2013-02-06 05:32
Also, note that if you attach with MenuDrawer.MENU_DRAG_WINDOW using the RightDrawer, everything works correctly.

**Comment by akshaydashrath** [comment] 2013-02-06 21:11
Theres another issue as well, even with my fix, if the menu size is set to default, on rotation the menu won't slide out as the new width is now the "height" when in portrait and the menu tries to slide to the same amount as the width when vertical.

A temporary workaround for this is to set a fixed width for the menu drawer

**Comment by SimonVT** [comment] 2013-02-12 17:15
Fixed on dev.

**Closed as completed by SimonVT** 2013-02-12 17:15 UTC
