### ISSUE TITLE
Force close while attempting to open the drawer with multiple fingers.

### ISSUE THREAD

**Issue by jerieljan** [SimonVT/android-menudrawer#122] opened 2013-05-24 02:01 UTC
I attempted this on the provided sample and my app before. Basically, try swiping the left side with multiple fingers. It's more likely to happen when done fast.

P.S. Oh and this only happens when the entire window is dragged. No problems so far when it's only the content area.

Here's the stack trace from logcat

``` java
E/AndroidRuntime(30683): FATAL EXCEPTION: main
E/AndroidRuntime(30683): java.lang.IllegalArgumentException: pointerIndex out of range
E/AndroidRuntime(30683):    at android.view.MotionEvent.nativeGetAxisValue(Native Method)
E/AndroidRuntime(30683):    at android.view.MotionEvent.getX(MotionEvent.java:1981)
E/AndroidRuntime(30683):    at net.simonvt.menudrawer.HorizontalDrawer.onInterceptTouchEvent(HorizontalDrawer.java:107)
E/AndroidRuntime(30683):    at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1817)
E/AndroidRuntime(30683):    at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2174)
E/AndroidRuntime(30683):    at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1917)
E/AndroidRuntime(30683):    at com.android.internal.policy.impl.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:1953)
E/AndroidRuntime(30683):    at com.android.internal.policy.impl.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1405)
E/AndroidRuntime(30683):    at android.app.Activity.dispatchTouchEvent(Activity.java:2414)
E/AndroidRuntime(30683):    at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:1901)
E/AndroidRuntime(30683):    at android.view.View.dispatchPointerEvent(View.java:7426)
E/AndroidRuntime(30683):    at android.view.ViewRootImpl.deliverPointerEvent(ViewRootImpl.java:3220)
E/AndroidRuntime(30683):    at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:3165)
E/AndroidRuntime(30683):    at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:4292)
E/AndroidRuntime(30683):    at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:4271)
E/AndroidRuntime(30683):    at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:4363)
E/AndroidRuntime(30683):    at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:179)
E/AndroidRuntime(30683):    at android.view.InputEventReceiver.nativeConsumeBatchedInputEvents(Native Method)
E/AndroidRuntime(30683):    at android.view.InputEventReceiver.consumeBatchedInputEvents(InputEventReceiver.java:171)
E/AndroidRuntime(30683):    at android.view.ViewRootImpl.doConsumeBatchedInput(ViewRootImpl.java:4342)
E/AndroidRuntime(30683):    at android.view.ViewRootImpl$ConsumeBatchedInputRunnable.run(ViewRootImpl.java:4382)
E/AndroidRuntime(30683):    at android.view.Choreographer$CallbackRecord.run(Choreographer.java:749)
E/AndroidRuntime(30683):    at android.view.Choreographer.doCallbacks(Choreographer.java:562)
E/AndroidRuntime(30683):    at android.view.Choreographer.doFrame(Choreographer.java:530)
E/AndroidRuntime(30683):    at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:735)
E/AndroidRuntime(30683):    at android.os.Handler.handleCallback(Handler.java:725)
E/AndroidRuntime(30683):    at android.os.Handler.dispatchMessage(Handler.java:92)
E/AndroidRuntime(30683):    at android.os.Looper.loop(Looper.java:137)
E/AndroidRuntime(30683):    at android.app.ActivityThread.main(ActivityThread.java:5234)
E/AndroidRuntime(30683):    at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime(30683):    at java.lang.reflect.Method.invoke(Method.java:525)
E/AndroidRuntime(30683):    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:799)
E/AndroidRuntime(30683):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:566)
E/AndroidRuntime(30683):    at dalvik.system.NativeStart.main(Native Method)
```

**Comment by Tolriq** [comment] 2013-05-24 23:24
Seems I checked the closed ones and not the opened ones ....

Since you close the other I post the edit here too :

And lint report in those files that 
MotionEvent.ACTION_POINTER_INDEX_MASK
is API 8 while the manifest allows API 7 as minimal.

**Comment by SimonVT** [comment] 2013-05-24 23:49
Fixed on dev.

@Tolriq Yes, I only really support multi touch on API8+. On API7 is just picks the pointer at index 0.

**Closed as completed by SimonVT** 2013-05-24 23:49 UTC

**Comment by Tolriq** [comment] 2013-05-25 00:09
Doing some crazy multi finger to test now :)

With last I trigger :

```
STACK_TRACE=java.lang.IllegalArgumentException: pointerIndex out of range
at android.view.MotionEvent.nativeGetAxisValue(Native Method)
at android.view.MotionEvent.getX(MotionEvent.java:1981)
at net.simonvt.menudrawer.HorizontalDrawer.onTouchEvent(SourceFile:198)
at android.view.View.dispatchTouchEvent(View.java:7246)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2168)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1903)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2174)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1917)
at com.android.internal.policy.impl.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:1953)
at com.android.internal.policy.impl.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1405)
at android.app.Activity.dispatchTouchEvent(Activity.java:2410)
at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:1901)
at android.view.View.dispatchPointerEvent(View.java:7426)
at android.view.ViewRootImpl.deliverPointerEvent(ViewRootImpl.java:3220)
at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:3165)
at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:4292)
at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:4271)
at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:4363)
at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:179)
at android.os.MessageQueue.nativePollOnce(Native Method)
at android.os.MessageQueue.next(MessageQueue.java:125)
at android.os.Looper.loop(Looper.java:124)
at android.app.ActivityThread.main(ActivityThread.java:5041)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:511)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:560)
at dalvik.system.NativeStart.main(Native Method)
```

**Comment by SimonVT** [comment] 2013-05-25 00:20
I can't reproduce that

**Comment by Tolriq** [comment] 2013-05-25 00:26
It's really multi finger frenetic actions to show / hide the menu.
